# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('courseId', models.IntegerField(default=-1)),
                ('courseName', models.CharField(max_length=30)),
                ('techerId', models.IntegerField(default=-1)),
                ('techerNumber', models.CharField(max_length=30)),
                ('techerName', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=200)),
                ('answerA', models.CharField(max_length=50)),
                ('answerB', models.CharField(max_length=50)),
                ('answerC', models.CharField(max_length=50)),
                ('answerD', models.CharField(max_length=50)),
                ('rightAnswer', models.CharField(max_length=30)),
                ('point', models.IntegerField(default=0)),
                ('courseId', models.IntegerField(default=-1)),
                ('courseName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('courseId', models.IntegerField(default=-1)),
                ('courseName', models.CharField(max_length=30)),
            ],
        ),
    ]
