# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_grade_question_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='stuId',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='grade',
            name='stuName',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='stuNumber',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
